repos:
  - repo: https://github.com/fastai/nbdev
    rev: 2.2.10
    hooks:
      - id: nbdev_clean

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.9

  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.2
    hooks:
      - id: pycln
        args: [. --all]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args:
          [
            "--profile",
            "black",
            "--filter-files",
            "--color",
            "--balanced",
            "--float-to-top",
          ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        exclude: ^docs/conf.py
        additional_dependencies:
          - types-dataclasses >= 0.1.3
          - types-PyYAML
          - tomli >= 0.2.6, < 2.0.0
          - types-typed-ast >= 1.4.1
          - click >= 8.1.0
          - packaging >= 22.0
          - platformdirs >= 2.1.0
          - pytest
          - hypothesis

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        exclude: '\.github/workflows/diff_shades\.yml|.*\.json$'

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
        args:
          - --no-allow-dict-kwargs
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-shebang-scripts-are-executable
      - id: pretty-format-json
        args:
          - --autofix
          - --no-sort-keys
          - --indent=4
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: requirements-txt-fixer

  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        args: [--in-place, --black]

  - repo: https://github.com/PyCQA/pydocstyle
    hooks:
      - id: pydocstyle
        name: pydocstyle
        entry: pydocstyle
        language: python
        types: [python]
        exclude: (.ci|.github)
        additional_dependencies:
          - toml
    rev: 6.1.1

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.28.0
    hooks:
      - id: yamllint
        name: yamllint
        description: This hook runs yamllint.
        entry: yamllint
        language: python
        types: [file, yaml]

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.0
    hooks:
      - id: nbqa-isort
        additional_dependencies: [isort==5.12.0]
        args: ["--profile=black", "--float-to-top"]
      - id: nbqa-black
        additional_dependencies: [black==23.3.0]
